#define EOF_TOK       0
#define INT_TOK       1
#define CHR_TOK       2
#define ASSIGN_TOK    3
#define SEMI_TOK      4
#define LPAREN_TOK    5
#define RPAREN_TOK    6
#define MINUS_TOK     7
#define PLUS_TOK      8
#define TIMES_TOK     9
#define DIV_TOK       10
#define LBRACE_TOK    11
#define RBRACE_TOK    12
#define COMMA_TOK     13
#define INTLIT_TOK    14
#define FLOATLIT_TOK  15
#define IDENT_TOK     16
